- ignore:
    name: "Use tuple-section"
- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use uncurry"
- ignore:
    name: "Reduce duplication"
- ignore:
    name: "Redundant do"
- ignore:
    name: "Use ++"
- ignore:
    name: "Use ||"
    within:
      - "Smos.Draw.drawEntry"
      - "Smos.Draw.drawEntryCursor"
- ignore:
    name: "Use camelCase"
    within: 
      - "Smos.Report.Archive.HideArchive"
      - "Smos.Scheduler"
- ignore: 
    name: "Use <$>"
    within: 
      - "Smos.Actions.Entry.TodoState.allTodoStatePlainActions"
      - "Smos.Report.Filter.astUnOpP"
- ignore: 
    name: "Avoid lambda"
- ignore: 
    name: "Eta reduce"
- ignore:
    name: "Redundant if"
    within:
      - "Smos.Draw.completedForestNumbersWidget"
      - "Smos.Sync.Client.Contents"
      - "Smos.Sync.Client.isHidden"
- ignore:
    name: "Replace case with maybe"
- ignore:
    name: "Use record patterns"
    within:
      - "Smos.Docs.Site.Handler.Keybindings"
      - "Smos.OptParse.Types"
